### PR TITLE
add AssemblyScript link

### LINKED ISSUE #9: What about mention AssemblyScript in "Cross-language comparison"?
[AssemblyScript](https://github.com/AssemblyScript/assemblyscript) already implement similar abilities along time ago. See [examples](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/operator-overloading.ts)

### PR DESCRIPTION
**Pull request by MaxGraey**
Close #9

### CODE REVIEW

**Comment by littledan** [comment]
Is there any documentation we can link to? If not, I'll merge this patch.

**Comment by MaxGraey** [comment]
Not so informative. Documentation is now a weak part:
https://github.com/AssemblyScript/assemblyscript/wiki/Built-ins#decorators

But this feature also mentioned in this article:
https://dev.to/jtenner/an-assemblyscript-primer-for-typescript-developers-lf1

**Comment by MaxGraey** [comment]
I think you can merge as is, there are no comments. WDYT?

**Comment by MaxGraey** [comment]
Thanks!

**Comment by littledan** [comment]
Thanks for the links--it's all really interesting.

**Pull request merged**
